"use strict";
let favouriteFood = "Briyani";
console.log(favouriteFood);
favouriteFood = "Karahi";
console.log(favouriteFood);
let yourName = "Mehjabin";
let surName = "Khan";
console.log(`My name is ${yourName} ${surName}.`);
let profession = ("Programmer");
console.log(`Hey there! I'm a ${profession}.`);
const yourAge = "20";
const eyeColor = "brown";
console.log(yourAge, eyeColor);
const mathsTestMarks = 45;
const scienceTestMarks = 50;
const totalMarks = mathsTestMarks + scienceTestMarks;
console.log(totalMarks);
